apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpointlisttest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: endpointlisttest
  template:
    metadata:
      labels:
        app: endpointlisttest
    spec:
      serviceAccountName: podlister-serviceaccount
      containers:
      - name: endpointlisttest
        image: martinfylke/endpointlisttest:latest
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: endpointlisttest
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: endpointlisttest
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: endpointlisttest-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  rules:
    - host: gpe-dev.volvocars.biz
      http:
        paths:
          - path: /listtest(/|$)(.*)
            backend:
              serviceName: endpointlisttest
              servicePort: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: podlister-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: podreader-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: podreader-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: podreader-role
subjects:
- kind: ServiceAccount
  name: podlister-serviceaccount