apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpointlisttest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: endpointlisttest
  template:
    metadata:
      labels:
        app: endpointlisttest
    spec:
      containers:
      - name: endpointlisttest
        image: martinfylke/endpointlisttest:latest
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: endpointlisttest
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: endpointlisttest
  type: LoadBalancer